In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [439]:
from datetime import datetime

now = datetime.now()
treino_data1 = datetime(1969, 12, 31, 21, 0, 0)
treino_data2 = datetime(2024, 3, 10, 10, 30, 0)

timestamp1 = int(now.timestamp())
timestamp2 = int(treino_data1.timestamp())
timestamp3 = int(treino_data2.timestamp())

print(timestamp1, timestamp2, timestamp1 - timestamp2, timestamp2 - timestamp3)

1724451914 0 1724451914 -1710077400

In [224]:
pr_calc = {"run": {'pace': 180, 
                   'pts': 0.27
                  },
           "trail": {'pace': 216, 
                     'pts': 0.27
                  },
           "road": {'pace': 90, 
                    'pts': 0.66
                  },
           "mtb": {'pace': 138, 
                   'pts': 0.45
                  }
          }
pr_calc

{'run': {'pace': 180, 'pts': 0.27},
 'trail': {'pace': 216, 'pts': 0.27},
 'road': {'pace': 90, 'pts': 0.66},
 'mtb': {'pace': 138, 'pts': 0.45}}

In [ ]:
modal, tp_bonus, val, tipo, inicio, bonus

In [223]:
pr_bonus = {"run": {"distancia": {'valor': 5, 'tipo': 'soma', 'inicio': 15, 'bonus': 0.015},
                    "altimetria": {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.01},
                    "idade": {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
                    "oly": {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
                    "competicao": {'valor': 1, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.05},
                    "feminino": {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}
                   },
            "trail": {"distancia": {'valor': 5, 'tipo': 'soma', 'inicio': 15, 'bonus': 0.015},
                    "altimetria": {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.01},
                    "idade": {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
                    "oly": {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
                    "competicao": {'valor': 1, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.05},
                    "feminino": {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}
                   },
            "road": {"distancia": {'valor': 5, 'tipo': 'soma', 'inicio': 15, 'bonus': 0.015},
                    "altimetria": {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.01},
                    "idade": {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
                    "oly": {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
                    "competicao": {'valor': 1, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.05},
                    "competicao": {'valor': 2, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.1},
                    "feminino": {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}
                   },
            "mtb": {"distancia": {'valor': 5, 'tipo': 'soma', 'inicio': 15, 'bonus': 0.015},
                    "altimetria": {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.01},
                    "idade": {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
                    "oly": {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
                    "competicao": {'valor': 1, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.05},
                    "feminino": {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}
                   }
            "walk": {"distancia": {'valor': 5, 'tipo': 'soma', 'inicio': 5, 'bonus': 0.015},
                    "altimetria": {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.01},
                    "idade": {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
                    "oly": {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
                    "feminino": {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}
                   }
            "water": {"distancia": {'valor': 5, 'tipo': 'soma', 'inicio': 10, 'bonus': 0.015},
                    "idade": {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
                    "oly": {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
                    "feminino": {'valor': 0, 'tipo': 'fixo'	 'inicio': 0, 'bonus': 0.12}
                   }
            "swim": {"distancia": {'valor': 0.1, 'tipo': 'soma', 'inicio': 0.1, 'bonus': 0.05},
                    "idade": {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
                    "oly": {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
                    "feminino": {'valor': 0, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.12}
                   }
           }
pr_bonus

{'run': {'distancia': {'valor': 5,
   'tipo': 'soma',
   'inicio': 15,
   'bonus': 0.015},
  'altimetria': {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.02},
  'idade': {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
  'oly': {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
  'competicao': {'valor': 1, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.05},
  'feminino': {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}},
 'trail': {'distancia': {'valor': 5,
   'tipo': 'soma',
   'inicio': 15,
   'bonus': 0.015},
  'altimetria': {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.02},
  'idade': {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
  'oly': {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
  'competicao': {'valor': 1, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.05},
  'feminino': {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}},
 'road': {'distancia': {'valor': 5,
   'tipo': 'soma',
   'inicio': 15,
   'bonus': 0.015},
  'altimetria': {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.02},
  'idade': {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
  'oly': {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
  'competicao': {'valor': 2, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.1},
  'feminino': {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}},
 'mtb': {'distancia': {'valor': 5,
   'tipo': 'soma',
   'inicio': 15,
   'bonus': 0.015},
  'altimetria': {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.02},
  'idade': {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015},
  'oly': {'valor': 1, 'tipo': 'fixo', 'inicio': 0, 'bonus': 0.1},
  'competicao': {'valor': 1, 'tipo': 'busca', 'inicio': 0, 'bonus': 0.05},
  'feminino': {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015}}}

In [398]:
def pr_treino(**treino):
    
    bonus = 0.0
    
    for chave, val_atl in treino.items():
        if chave != "tipo" and chave != "pace":
            
            if pr_bonus.get(treino['tipo']):
            
                if ((pr_bonus[treino['tipo']][chave]['tipo'] == 'fixo') and 
                    (pr_bonus[treino['tipo']][chave]['valor'] == val_atl)):
                    bonus += pr_bonus[treino['tipo']][chave]['bonus']
                    print(chave, pr_bonus[treino['tipo']][chave], bonus)
                
                if pr_bonus[treino['tipo']][chave]['tipo'] == 'soma':
                    bon_tmp = pr_bonus[treino['tipo']][chave]['bonus']
                    inicio = pr_bonus[treino['tipo']][chave]['inicio']
                    valor = pr_bonus[treino['tipo']][chave]['valor']
                    
                    if valor:
                        bonus += bon_tmp * ((val_atl - inicio) / valor)
                    print(chave, pr_bonus[treino['tipo']][chave], (bon_tmp * ((val_atl - inicio) / valor)), bonus)
                
    if pr_calc.get(treino['tipo']):
        pace_calca = pr_calc[treino['tipo']].get('pace')
        pts_calca = pr_calc[treino['tipo']].get('pts')
        
        print(treino['pace'], pace_calca, pts_calca, bonus)
        
        calcula = (treino['pace'] - pace_calca) * (1 - bonus) * pts_calca
        
        if calcula < 1: calcula = 1
        if calcula > 100: calcula = 100
            
    return calcula

In [216]:
dist = 3134.4
tempo = 837
pace = tempo / (dist / 1000)
dist / tempo

3.7448028673835125

In [217]:
print( pace)

267.0367534456355

In [391]:
tipo = 'road'
pace = 137.5
distancia = 62.2
altimetria = 347
idade = 51
oly = 0
competicao = 0
feminino = 0

In [280]:
tipo = 'road'
pace = 267.0367534456355
pace = 199.5
distancia = 3.1344
distancia = 15
altimetria = 47
altimetria = 0
idade = 51
oly = 0
competicao = 0
feminino = 0

In [392]:
print(tipo, pace, distancia, altimetria, idade, oly, competicao, feminino)

road 137.5 62.2 347 51 0 0 0

In [399]:
pr_treino(tipo = tipo,
          pace = pace,
          distancia = distancia,
          altimetria = altimetria,
          idade = idade,
          oly = oly,
          competicao = competicao,
          feminino = feminino)  #tipo, distancia, altimetria, idade, oly, competicao, feminino

distancia {'valor': 5, 'tipo': 'soma', 'inicio': 15, 'bonus': 0.015} 0.1416 0.1416
altimetria {'valor': 100, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.02} 0.0694 0.21100000000000002
idade {'valor': 5, 'tipo': 'soma', 'inicio': 30, 'bonus': 0.015} 0.063 0.274
feminino {'valor': 5, 'tipo': 'soma', 'inicio': 0, 'bonus': 0.015} 0.0 0.274
137.5 90 0.66 0.274

22.7601

In [396]:
137.5 * (1 - .274)

99.825

In [ ]:
print(chave, pr_bonus[treino['tipo']][chave], bonus)

In [245]:
# GARMIN / STRAVA
#
# LOOP GARMIN

atleta = 123123123
treino_data = datetime(2024, 3, 10, 10, 30, 0)
semana_treino = treino_data.strftime("%V")
semana_tr_int = int(semana_treino)
tipo = 'run'
pace = 240
distancia = 21
altimetria = 0
idade = 47
oly = 0
competicao = 0
feminino = 21

In [248]:
prx_treino = pr_treino(tipo = tipo,
                       pace = pace,
                       distancia = distancia,
                       altimetria = altimetria,
                       idade = idade,
                       oly = oly,
                       competicao = competicao,
                       feminino = feminino)
retorno = carrega_treino(atleta, semana_tr_int, prx_treino, 0, retorno)
retorno

123123123 10 14.0616

[123123123,
 2024,
 '2024-01-01',
 [40.0, 5],
 [42.0, 6],
 [44.1, 7],
 [46.30500000000001, 7],
 [48.620250000000006, 7],
 [37.949512500000004, 3],
 [39.846988125, 4],
 [32.75239641679688, 3],
 [20.464379431172958, 3],
 [17.194443076152396, 3],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0],
 [0.0, 0]]

In [415]:
import pandas as pd

# Criar um dicionário com datas, incluindo uma data nula usando None
def gera_novo(idatl):
    data_dict = {
    'id_atl': [idatl, idatl, idatl, idatl, idatl],
    'sport': ['RUN', 'ROAD', 'SWIM', 'TRAIL', 'MTB'],
    'ano': [2024, 2024, 2024, 2024, 2024],
    'data': [None, None, None, None, None],
    'qtd_tr': [3, 3, 3, 3, 3],
    'avg_tr': [50.0, 50.0, 50.0, 50.0, 50.0],
    'dsv_tr': [33.0, 33.0, 33.0, 33.0, 33.0],
    'pr1': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr1': [0, 0, 0, 0, 0],
    'pr2': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr2': [0, 0, 0, 0, 0],
    'pr3': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr3': [0, 0, 0, 0, 0],
    'pr4': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr4': [0, 0, 0, 0, 0],
    'pr5': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr5': [0, 0, 0, 0, 0],
    'pr6': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr6': [0, 0, 0, 0, 0],
    'pr7': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr7': [0, 0, 0, 0, 0],
    'pr8': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr8': [0, 0, 0, 0, 0],
    'pr9': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr9': [0, 0, 0, 0, 0],
    'pr10': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr10': [0, 0, 0, 0, 0],
    'pr11': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr11': [0, 0, 0, 0, 0],
    'pr12': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr12': [0, 0, 0, 0, 0],
    'pr13': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr13': [0, 0, 0, 0, 0],
    'pr14': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr14': [0, 0, 0, 0, 0],
    'pr15': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr15': [0, 0, 0, 0, 0],
    'pr16': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr16': [0, 0, 0, 0, 0],
    'pr17': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr17': [0, 0, 0, 0, 0],
    'pr18': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr18': [0, 0, 0, 0, 0],
    'pr19': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr19': [0, 0, 0, 0, 0],
    'pr20': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr20': [0, 0, 0, 0, 0],
    'pr21': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr21': [0, 0, 0, 0, 0],
    'pr22': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr22': [0, 0, 0, 0, 0],
    'pr23': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr23': [0, 0, 0, 0, 0],
    'pr24': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr24': [0, 0, 0, 0, 0],
    'pr25': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr25': [0, 0, 0, 0, 0],
    'pr26': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr26': [0, 0, 0, 0, 0],
    'pr27': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr27': [0, 0, 0, 0, 0],
    'pr28': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr28': [0, 0, 0, 0, 0],
    'pr29': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr29': [0, 0, 0, 0, 0],
    'pr30': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr30': [0, 0, 0, 0, 0],
    'pr31': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr31': [0, 0, 0, 0, 0],
    'pr32': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr32': [0, 0, 0, 0, 0],
    'pr33': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr33': [0, 0, 0, 0, 0],
    'pr34': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr34': [0, 0, 0, 0, 0],
    'pr35': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr35': [0, 0, 0, 0, 0],
    'pr36': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr36': [0, 0, 0, 0, 0],
    'pr37': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr37': [0, 0, 0, 0, 0],
    'pr38': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr38': [0, 0, 0, 0, 0],
    'pr39': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr39': [0, 0, 0, 0, 0],
    'pr40': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr40': [0, 0, 0, 0, 0],
    'pr41': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr41': [0, 0, 0, 0, 0],
    'pr42': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr42': [0, 0, 0, 0, 0],
    'pr43': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr43': [0, 0, 0, 0, 0],
    'pr44': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr44': [0, 0, 0, 0, 0],
    'pr45': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr45': [0, 0, 0, 0, 0],
    'pr46': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr46': [0, 0, 0, 0, 0],
    'pr47': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr47': [0, 0, 0, 0, 0],
    'pr48': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr48': [0, 0, 0, 0, 0],
    'pr49': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr49': [0, 0, 0, 0, 0],
    'pr50': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr50': [0, 0, 0, 0, 0],
    'pr51': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr51': [0, 0, 0, 0, 0],
    'pr52': [0.0, 0.0, 0.0, 0.0, 0.0],
    'tr52': [0, 0, 0, 0, 0]
    }

    # Converter o dicionário em um DataFrame
    df = pd.DataFrame(data_dict)

    # Converter a coluna 'Data' para o tipo datetime
    df['data'] = pd.to_datetime(df['data'])

    return df

In [416]:
df_week = gera_novo(1)
df_week

,id_atl,sport,ano,data,qtd_tr,avg_tr,dsv_tr,pr1,tr1,pr2,...,pr48,tr48,pr49,tr49,pr50,tr50,pr51,tr51,pr52,tr52
0,1,RUN,2024,NaT,3,50.0,33.0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
1,1,ROAD,2024,NaT,3,50.0,33.0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
2,1,SWIM,2024,NaT,3,50.0,33.0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
3,1,TRAIL,2024,NaT,3,50.0,33.0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
4,1,MTB,2024,NaT,3,50.0,33.0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0

In [54]:
df_week = gera_novo(1)
sportx = 'MTB'
atl_ano_sem = df_week[df_week['id_atl'].isin([sportx])].reset_index(drop=True)
atl_ano_sem

,id_atl,ano,data,pr1,tr1,pr2,tr2,pr3,tr3,pr4,...,pr48,tr48,pr49,tr49,pr50,tr50,pr51,tr51,pr52,tr52
0,MTB,2024,NaT,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0

In [32]:
soma_pr = 0
for i in range(52):
    campo = 'pr' + str(int(i+1))
    soma_pr += atl_ano_sem[campo]
print(soma_pr)

0    0.0
Name: pr1, dtype: float64

In [ ]:
atl = 1
novo = 1
now = datetime.now()
semana = now.isocalendar()[1]

carrega_treino(atl, semana, novo)

In [378]:
atividades = pd.read_csv("strava_chris_1_de_janeiro_2024.csv")
atividades[atividades['sport_type'] == 'SWIM']

,id,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,start_date,location_city,location_state,...,external_id,pr_count,stravaConnectionId,createdAt,updatedAt,gender,age,score,week,wasCalculated
6,12038,2057.4,2448,2453,0.0,Swim,SWIM,2024-08-27 00:01:06,NaN,NaN,...,stripped_garmin_ping_365520568831,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,0.0,35,False
11,12043,1851.7,2769,2806,0.0,Swim,SWIM,2024-08-23 23:57:53,NaN,NaN,...,stripped_garmin_ping_364770254444,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,0.0,34,False
17,12049,1874.5,2403,2413,0.0,Swim,SWIM,2024-08-20 00:11:08,NaN,NaN,...,stripped_garmin_ping_363784667219,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.933,2024-08-30 19:37:37.933,male,51,0.0,34,False
22,12054,1943.1,2482,2488,0.0,Swim,SWIM,2024-08-17 00:00:56,NaN,NaN,...,stripped_garmin_ping_363471293857,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.933,2024-08-30 19:37:37.933,male,51,0.0,33,False
29,12061,1851.7,3085,3111,0.0,Swim,SWIM,2024-08-11 18:29:09,NaN,NaN,...,stripped_garmin_ping_361741505751,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.933,2024-08-30 19:37:37.933,male,51,0.0,32,False
39,12071,1897.4,2572,2593,0.0,Swim,SWIM,2024-08-05 23:59:47,NaN,NaN,...,stripped_garmin_ping_360316483970,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.934,2024-08-30 19:37:37.934,male,51,0.0,32,False
47,12079,1828.8,2182,2217,0.0,Swim,SWIM,2024-07-30 00:03:52,NaN,NaN,...,stripped_garmin_ping_358607635735,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.935,2024-08-30 19:37:37.935,male,51,0.0,31,False
58,12090,1874.5,2299,2308,0.0,Swim,SWIM,2024-07-24 02:18:32,NaN,NaN,...,stripped_garmin_ping_357173202341,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.935,2024-08-30 19:37:37.935,male,51,0.0,30,False
65,12097,1851.7,2166,2185,0.0,Swim,SWIM,2024-07-18 18:51:42,NaN,NaN,...,stripped_garmin_ping_355893759491,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.936,2024-08-30 19:37:37.936,male,51,0.0,29,False
69,12101,1828.8,2369,2455,0.0,Swim,SWIM,2024-07-16 00:07:36,NaN,NaN,...,stripped_garmin_ping_355229963872,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.936,2024-08-30 19:37:37.936,male,51,0.0,29,False
72,12104,142.3,260,260,0.0,Swim,SWIM,2024-07-14 18:31:47,NaN,NaN,...,stripped_garmin_ping_354913530320,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.936,2024-08-30 19:37:37.936,male,51,0.0,28,False
76,12108,1577.3,2117,2176,0.0,Swim,SWIM,2024-07-13 00:14:19,NaN,NaN,...,stripped_garmin_ping_354494133229,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.936,2024-08-30 19:37:37.936,male,51,0.0,28,False
80,12112,617.2,1271,1278,0.0,Swim,SWIM,2024-07-09 00:58:11,NaN,NaN,...,stripped_garmin_ping_353550061645,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.936,2024-08-30 19:37:37.936,male,51,0.0,28,False
113,12145,2080.3,2553,2597,0.0,Swim,SWIM,2024-06-10 23:53:45,NaN,NaN,...,stripped_garmin_ping_346925565836,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.938,2024-08-30 19:37:37.938,male,51,0.0,24,False
120,12152,1760.2,2080,2095,0.0,Swim,SWIM,2024-06-05 23:56:53,NaN,NaN,...,stripped_garmin_ping_345744010582,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.938,2024-08-30 19:37:37.938,male,51,0.0,23,False
125,12157,2651.8,3003,3106,0.0,Swim,SWIM,2024-05-31 14:57:33,NaN,NaN,...,stripped_garmin_ping_344447999587,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.939,2024-08-30 19:37:37.939,male,51,0.0,22,False
129,12161,2423.2,3176,3199,0.0,Swim,SWIM,2024-05-29 14:55:24,NaN,NaN,...,stripped_garmin_ping_343983552752,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.939,2024-08-30 19:37:37.939,male,51,0.0,22,False
137,12169,2560.3,3567,3611,0.0,Swim,SWIM,2024-05-24 14:56:28,NaN,NaN,...,stripped_garmin_ping_342812433305,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.939,2024-08-30 19:37:37.939,male,51,0.0,21,False
146,12178,177.9,74,74,0.0,Swim,SWIM,2024-05-22 02:37:46,NaN,NaN,...,stripped_garmin_ping_342207894516,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.94,2024-08-30 19:37:37.94,male,51,0.0,21,False
148,12180,2514.6,3351,3359,0.0,Swim,SWIM,2024-05-22 01:05:25,NaN,NaN,...,stripped_garmin_ping_342203293603,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.94,2024-08-30 19:37:37.94,male,51,0.0,21,False
156,12188,2331.7,2662,2669,0.0,Swim,SWIM,2024-05-17 23:58:30,NaN,NaN,...,stripped_garmin_ping_341247732725,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.94,2024-08-30 19:37:37.94,male,51,0.0,20,False
162,12194,2126.0,2572,2646,0.0,Swim,SWIM,2024-05-15 01:32:33,NaN,NaN,...,stripped_garmin_ping_340571643111,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.94,2024-08-30 19:37:37.94,male,51,0.0,20,False
174,12206,2126.0,2504,2522,0.0,Swim,SWIM,2024-05-07 00:02:08,NaN,NaN,...,stripped_garmin_ping_338691246333,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.941,2024-08-30 19:37:37.941,male,51,0.0,19,False
180,12212,1714.5,2930,2963,0.0,Swim,SWIM,2024-05-03 09:27:36,NaN,NaN,...,stripped_garmin_ping_337854554107,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.941,2024-08-30 19:37:37.941,male,51,0.0,18,False
204,12236,1828.8,2245,2258,0.0,Swim,SWIM,2024-04-16 00:11:34,NaN,NaN,...,stripped_garmin_ping_333891798595,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.942,2024-08-30 19:37:37.942,male,51,0.0,16,False
214,12246,1828.8,2130,2147,0.0,Swim,SWIM,2024-04-11 00:07:37,NaN,NaN,...,stripped_garmin_ping_332792191096,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.943,2024-08-30 19:37:37.943,male,51,0.0,15,False
218,12250,1828.8,2282,2289,0.0,Swim,SWIM,2024-04-09 00:06:39,NaN,NaN,...,stripped_garmin_ping_332357385833,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.943,2024-08-30 19:37:37.943,male,51,0.0,15,False
236,12268,1257.3,2432,2442,0.0,Swim,SWIM,2024-03-27 23:59:18,NaN,NaN,...,stripped_garmin_ping_329735726489,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.944,2024-08-30 19:37:37.944,male,51,0.0,13,False
241,12273,2057.4,2417,2449,0.0,Swim,SWIM,2024-03-26 00:08:04,NaN,NaN,...,garmin_ping_329311745839,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.944,2024-08-30 19:37:37.944,male,51,0.0,13,False
252,12284,2011.7,2712,2737,0.0,Swim,SWIM,2024-03-19 00:04:05,NaN,NaN,...,garmin_ping_327840802785,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.945,2024-08-30 19:37:37.945,male,51,0.0,12,False
259,12291,2011.7,2721,2742,0.0,Swim,SWIM,2024-03-14 00:05:12,NaN,NaN,...,garmin_ping_326788037927,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.945,2024-08-30 19:37:37.945,male,51,0.0,11,False
275,12307,1851.7,2386,2551,0.0,Swim,SWIM,2024-02-29 01:03:19,NaN,NaN,...,garmin_ping_323882885052,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.946,2024-08-30 19:37:37.946,male,51,0.0,9,False
279,12311,2286.0,2787,2794,0.0,Swim,SWIM,2024-02-27 00:50:42,NaN,NaN,...,garmin_ping_323486789100,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.946,2024-08-30 19:37:37.946,male,51,0.0,9,False
285,12317,2194.6,2518,2537,0.0,Swim,SWIM,2024-02-22 00:43:42,NaN,NaN,...,garmin_ping_322523391302,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.946,2024-08-30 19:37:37.946,male,51,0.0,8,False
298,12330,1920.2,2229,2234,0.0,Swim,SWIM,2024-02-15 00:55:11,NaN,NaN,...,garmin_ping_321183819051,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.947,2024-08-30 19:37:37.947,male,51,0.0,7,False
304,12336,2194.6,2700,2715,0.0,Swim,SWIM,2024-02-13 01:01:18,NaN,NaN,...,garmin_ping_320804538535,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.947,2024-08-30 19:37:37.947,male,51,0.0,7,False
310,12342,1966.0,2774,2785,0.0,Swim,SWIM,2024-02-08 01:00:55,NaN,NaN,...,garmin_ping_319861416330,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.947,2024-08-30 19:37:37.947,male,51,0.0,6,False
313,12345,1074.4,1240,1250,0.0,Swim,SWIM,2024-02-06 01:00:49,NaN,NaN,...,garmin_ping_319476359985,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.948,2024-08-30 19:37:37.948,male,51,0.0,6,False
327,12359,2263.1,2830,2875,0.0,Swim,SWIM,2024-01-30 01:04:46,NaN,NaN,...,garmin_ping_318145205247,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.948,2024-08-30 19:37:37.948,male,51,0.0,5,False
330,12362,2263.1,2890,2916,0.0,Swim,SWIM,2024-01-27 23:28:56,NaN,NaN,...,garmin_ping_317750066765,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.948,2024-08-30 19:37:37.948,male,51,0.0,4,False
340,12372,2194.6,2616,2675,0.0,Swim,SWIM,2024-01-25 01:01:48,NaN,NaN,...,garmin_ping_317217465648,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.949,2024-08-30 19:37:37.949,male,51,0.0,4,False
346,12378,1943.1,2506,2513,0.0,Swim,SWIM,2024-01-20 00:54:30,NaN,NaN,...,garmin_ping_316278522596,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.949,2024-08-30 19:37:37.949,male,51,0.0,3,False
355,12387,2148.8,2551,2566,0.0,Swim,SWIM,2024-01-13 00:59:38,NaN,NaN,...,garmin_ping_315001498960,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.949,2024-08-30 19:37:37.949,male,51,0.0,2,False
366,12398,1440.2,2383,2394,0.0,Swim,SWIM,2024-01-02 20:41:55,NaN,NaN,...,garmin_ping_313083813741,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,0.0,1,False

In [377]:
x = atividades[atividades['wasCalculated'].isin([True])].sort_values(["sport_type", "start_date"])
x

,id,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,start_date,location_city,location_state,...,external_id,pr_count,stravaConnectionId,createdAt,updatedAt,gender,age,score,week,wasCalculated
13,12045,24683.0,5496,5785,159.0,Ride,MTB,2024-08-22 15:49:49,NaN,NaN,...,stripped_garmin_ping_364452379958,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,29.07,34,True
10,12042,44033.3,8984,9742,397.1,Ride,MTB,2024-08-24 15:35:03,NaN,NaN,...,stripped_garmin_ping_364952354407,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,12.54,34,True
3,12035,26260.6,5683,6032,226.1,Ride,MTB,2024-08-28 14:39:04,NaN,NaN,...,stripped_garmin_ping_365936288440,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,25.37,35,True
368,12400,62192.9,8553,8971,347.0,Ride,ROAD,2024-01-01 18:21:21,NaN,NaN,...,garmin_ping_312869566562,4,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,23.00,1,True
363,12395,51199.4,7691,8028,524.0,Ride,ROAD,2024-01-07 18:17:52,NaN,NaN,...,garmin_ping_314027221368,1,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,28.65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,12036,8010.9,2449,2449,41.0,Run,RUN,2024-08-28 01:02:24,NaN,NaN,...,stripped_garmin_ping_365785056040,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,32.31,35,True
2,12034,7029.6,2220,2319,38.0,Run,RUN,2024-08-29 16:06:21,NaN,NaN,...,stripped_garmin_ping_366188348308,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,35.01,35,True
1,12033,2605.4,923,1023,10.0,Run,RUN,2024-08-29 16:46:37,NaN,NaN,...,stripped_garmin_ping_366191923150,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,45.67,35,True
36,12068,667.9,469,484,18.0,Run,TRAIL,2024-08-06 19:34:35,NaN,NaN,...,stripped_garmin_ping_360516698914,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.933,2024-08-30 19:37:37.933,male,51,100.00,32,True
9,12041,8281.5,3133,3133,93.0,Run,TRAIL,2024-08-25 17:26:42,NaN,NaN,...,stripped_garmin_ping_365199733112,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,41.05,34,True

In [390]:
8553 / 62.1929

137.52373663231654

In [353]:
x = atividades[atividades['score'] > 70]

In [243]:
atividades.columns

Index(['id', 'distance', 'moving_time', 'elapsed_time', 'total_elevation_gain',
       'type', 'sport_type', 'start_date', 'location_city', 'location_state',
       'location_country', 'athlete_count', 'trainer', 'commute', 'manual',
       'private', 'gear_id', 'average_speed', 'max_speed', 'has_heartrate',
       'heartrate_opt_out', 'display_hide_heartrate_option', 'elev_high',
       'elev_low', 'upload_id_str', 'external_id', 'pr_count',
       'stravaConnectionId', 'createdAt', 'updatedAt', 'gender', 'age',
       'score', 'week', 'wasCalculated'],
      dtype='object')

In [246]:
atividades.head()

,id,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,start_date,location_city,location_state,...,external_id,pr_count,stravaConnectionId,createdAt,updatedAt,gender,age,score,week,wasCalculated
0,12032,2400.4,1741,2791,3.0,Hike,HIKE,2024-08-30 15:53:53,NaN,NaN,...,stripped_garmin_ping_366432639852,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,0.00,35,False
1,12033,2605.4,923,1023,10.0,Run,RUN,2024-08-29 16:46:37,NaN,NaN,...,stripped_garmin_ping_366191923150,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,45.67,35,True
2,12034,7029.6,2220,2319,38.0,Run,RUN,2024-08-29 16:06:21,NaN,NaN,...,stripped_garmin_ping_366188348308,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,35.01,35,True
3,12035,26260.6,5683,6032,226.1,Ride,MTB,2024-08-28 14:39:04,NaN,NaN,...,stripped_garmin_ping_365936288440,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,25.37,35,True
4,12036,8010.9,2449,2449,41.0,Run,RUN,2024-08-28 01:02:24,NaN,NaN,...,stripped_garmin_ping_365785056040,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,32.31,35,True

In [413]:
atividades["gear_id"]

0       g13263
1       g13263
2       g13263
3      b120709
4       g13263
        ...
364     g13263
365     g13263
366        NaN
367     g13263
368    b120709
Name: gear_id, Length: 369, dtype: object

In [414]:
atividades

,id,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,start_date,location_city,location_state,...,external_id,pr_count,stravaConnectionId,createdAt,updatedAt,gender,age,score,week,wasCalculated
0,12032,2400.4,1741,2791,3.0,Hike,HIKE,2024-08-30 15:53:53,NaN,NaN,...,stripped_garmin_ping_366432639852,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,0.00,35,False
1,12033,2605.4,923,1023,10.0,Run,RUN,2024-08-29 16:46:37,NaN,NaN,...,stripped_garmin_ping_366191923150,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,45.67,35,True
2,12034,7029.6,2220,2319,38.0,Run,RUN,2024-08-29 16:06:21,NaN,NaN,...,stripped_garmin_ping_366188348308,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,35.01,35,True
3,12035,26260.6,5683,6032,226.1,Ride,MTB,2024-08-28 14:39:04,NaN,NaN,...,stripped_garmin_ping_365936288440,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,25.37,35,True
4,12036,8010.9,2449,2449,41.0,Run,RUN,2024-08-28 01:02:24,NaN,NaN,...,stripped_garmin_ping_365785056040,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.932,2024-08-30 19:37:37.932,male,51,32.31,35,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,12396,9051.8,3168,3222,66.0,Run,RUN,2024-01-07 00:11:14,NaN,NaN,...,garmin_ping_313875639704,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,43.22,1,True
365,12397,10476.7,3359,3359,44.0,Run,RUN,2024-01-04 18:26:19,NaN,NaN,...,garmin_ping_313460584436,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,35.85,1,True
366,12398,1440.2,2383,2394,0.0,Swim,SWIM,2024-01-02 20:41:55,NaN,NaN,...,garmin_ping_313083813741,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,0.00,1,False
367,12399,7162.0,2496,2496,70.0,Run,RUN,2024-01-02 19:06:21,NaN,NaN,...,garmin_ping_313070004321,0,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,43.19,1,True
368,12400,62192.9,8553,8971,347.0,Ride,ROAD,2024-01-01 18:21:21,NaN,NaN,...,garmin_ping_312869566562,4,clx50in7e00018mc4q47nywua,2024-08-30 19:37:37.95,2024-08-30 19:37:37.95,male,51,23.00,1,True

In [82]:
semana_atual

35

In [118]:
now = datetime.now()
semana_atual = now.isocalendar()[1]
carrega_treino(1, semana_atual, 1)

 MountainBikeRide
30.29
MountainBikeRide Run

In [260]:
import math
def acerta_desvio(n, media, desvio, novo_valor):
    # Calcular a nova média
    nova_media = (n * media + novo_valor) / (n + 1)
    
    # Calcular a soma dos quadrados das diferenças para o desvio padrão atual
    ssq = n * desvio**2
    
    # Calcular a nova soma dos quadrados das diferenças
    nova_ssq = ssq + (novo_valor - media) * (novo_valor - nova_media)
    
    # Calcular o novo desvio padrão
    novo_desvio = math.sqrt(nova_ssq / (n + 1))
    
    return nova_media, novo_desvio

In [267]:
acerta_desvio(2, 12.5, 2.5, 12.5)

(12.5, 2.041241452319315)

In [417]:
#
# Rotina de coloca na semana treinos novos
#
# tem que plugar o banco de dados
#
#
#
#
#

import math

def calculate_week_year_by_date(date_str):
    date = datetime.strptime(date_str, '%Y-%m-%dT%H:%M:%SZ')
    week_year = date.isocalendar()[1]

    return week_year

def acerta_desvio(n, media, desvio, novo_valor):
    nova_media = (n * media + novo_valor) / (n + 1)
    
    ssq = n * desvio**2
    nova_ssq = ssq + (novo_valor - media) * (novo_valor - nova_media)

    novo_desvio = math.sqrt(nova_ssq / (n + 1))
    
    return nova_media, novo_desvio
    
def carrega_treino_novo(atl, semana, novo):
    
    #=================
    
    # Chama dados
    
    if novo:
        # Carrega dataframe com os PR por esporte
        df_week = gera_novo(atl)
    
    # Carregas dados de treino do atleta
    
    atividades = pd.read_csv("strava_chris_1_de_janeiro_2024.csv")
    atividades = atividades[atividades['wasCalculated'].isin([True])].sort_values(["sport_type", "start_date"])
    
    #=================
    
    controle = 0
    atv_anterior = ""
    now = datetime.now()
    semana_atual = now.isocalendar()[1]
    ano_atual = now.year
    semana_util = 0
    semana_util_ant = 0
    
    #=================
    
    for atv in atividades.itertuples():
        # pace_orig = (atv.moving_time * 1000.0) / atv.distance
        if atv_anterior != atv.sport_type:
            if controle > 0:
                semana_util = semana_util + 1
                
                while semana_util <= semana_atual:
                    semana_treino_ant = 'pr'+ str(int(semana_util - 1))
                    qtd_treino_ant = 'tr'+ str(int(semana_util - 1))
                    semana_treino = 'pr'+ str(int(semana_util))
                    qtd_treino = 'tr'+ str(int(semana_util))

                    val_temp = df_week.loc[atl_index, semana_treino_ant] * 1.05
                    qtd_temp = df_week.loc[atl_index, qtd_treino_ant] + 1

                    if val_temp > 100:
                        val_temp = 100

                    if qtd_temp > 7:
                        qtd_temp = 7

                    df_week.at[atl_index, semana_treino] = val_temp
                    df_week.at[atl_index, qtd_treino] = qtd_temp

                    semana_util += 1

            controle = 0
        
        if controle == 0:
            
            if atv.sport_type == 'MountainBikeRide' and int(atv.distance) < 5000: continue
            if atv.sport_type == 'Run' and int(atv.distance) < 2000: continue
            if atv.sport_type == 'Ride' and int(atv.distance) < 5000: continue
            if atv.sport_type == 'Swim' and int(atv.distance) < 800: continue
            if atv.sport_type == 'TrailRun' and int(atv.distance) < 2000: continue
            
            sportx = atv.sport_type
            if atv.sport_type == 'MountainBikeRide': sportx = 'MTB'
            if atv.sport_type == 'Run': sportx = 'RUN'
            if atv.sport_type == 'Ride': sportx = 'ROAD'
            if atv.sport_type == 'Swim': sportx = 'SWIM'
            if atv.sport_type == 'TrailRun': sportx = 'TRAIL'
    
            atl_index = df_week[(df_week['sport'] == sportx) & (df_week['ano'] == ano_atual)].index[0]
            atv_anterior = atv.sport_type
        
        if controle == 0:
            soma_pr = int(0)
            for i in range(52):
                campo = 'pr' + str(int(i+1))
                soma_pr += df_week.loc[atl_index, campo]
            
            controle = 1
            if (soma_pr == 0.0).item():
                semana_util = int(atv.week)
                semana_util_ant = semana_util
                semana_treino = 'pr'+ str(semana_util)
                qtd_treino = 'tr'+ str(semana_util)
                df_week.at[atl_index, semana_treino] = atv.score
                df_week.at[atl_index, qtd_treino] = 3
                df_week.at[atl_index, 'data'] = atv.start_date
                
                nova_media, novo_desvio = acerta_desvio(df_week.loc[atl_index, 'qtd_tr'], df_week.loc[atl_index, 'avg_tr'], df_week.loc[atl_index, 'dsv_tr'], atv.score)
                
                df_week.at[atl_index, 'qtd_tr'] = df_week.loc[atl_index, 'qtd_tr'] + 1
                df_week.at[atl_index, 'avg_tr'] = nova_media
                df_week.at[atl_index, 'dsv_tr'] = novo_desvio
                #print(df_week.loc[atl_index, 'qtd_tr'], df_week.loc[atl_index, 'avg_tr'], df_week.loc[atl_index, 'dsv_tr'])
                
                continue

        semana_util = int(atv.week)
        semana_treino = 'pr'+ str(semana_util)
        qtd_treino = 'tr'+ str(semana_util)
        
        if semana_util > semana_util_ant:
            semana_util_ant = semana_util_ant + 1
                
            while semana_util_ant <= semana_util:
                semana_treino_ant = 'pr'+ str(int(semana_util_ant - 1))
                qtd_treino_ant = 'tr'+ str(int(semana_util_ant - 1))
                semana_treino = 'pr'+ str(int(semana_util_ant))
                qtd_treino = 'tr'+ str(int(semana_util_ant))

                val_temp = df_week.loc[atl_index, semana_treino_ant] * 1.05
                qtd_temp = df_week.loc[atl_index, qtd_treino_ant] + 1

                if val_temp > 100: val_temp = 100
                if qtd_temp > 7: qtd_temp = 7

                df_week.at[atl_index, semana_treino] = val_temp
                df_week.at[atl_index, qtd_treino] = qtd_temp

                semana_util_ant += 1
        
        semana_util_ant = semana_util
        
        min_pace = 0.0
        max_pace = 0.0
        if df_week.loc[atl_index, 'qtd_tr'] >= 3:
            min_pace = df_week.loc[atl_index, 'avg_tr'] - (2 * df_week.loc[atl_index, 'dsv_tr'])
            max_pace = df_week.loc[atl_index, 'avg_tr'] + (2 * df_week.loc[atl_index, 'dsv_tr'])
            
            # print(min_pace, atv.score, max_pace)
            if min_pace > atv.score or atv.score > max_pace: continue
        
        val_calc = df_week.loc[atl_index, semana_treino]
        qtd_calc = df_week.loc[atl_index, qtd_treino] - 1
        
        if qtd_calc < 3: qtd_calc = 3
        
        #print(semana_util, 'antes', atv.score, val_calc, qtd_calc, min_pace, pace_orig, max_pace)
        
        val_calc = (atv.score + val_calc * qtd_calc) / (qtd_calc + 1)

        #print(semana_util, 'depois', atv.score, val_calc, qtd_calc)        
        
        if val_calc < 1: val_calc = 1
        if val_calc > 100: val_calc = 100

        df_week.at[atl_index, semana_treino] = val_calc
        df_week.at[atl_index, qtd_treino] = qtd_calc
        
        df_week.at[atl_index, 'data'] = atv.start_date
                
        nova_media, novo_desvio = acerta_desvio(df_week.loc[atl_index, 'qtd_tr'], df_week.loc[atl_index, 'avg_tr'], df_week.loc[atl_index, 'dsv_tr'], atv.score)
                
        df_week.at[atl_index, 'qtd_tr'] = df_week.loc[atl_index, 'qtd_tr'] + 1
        df_week.at[atl_index, 'avg_tr'] = nova_media
        df_week.at[atl_index, 'dsv_tr'] = novo_desvio
        #print(min_pace, atv.score, max_pace)
        
    if controle > 0:
        semana_util = semana_util + 1
                
        while semana_util <= semana_atual:
            semana_treino_ant = 'pr'+ str(int(semana_util - 1))
            qtd_treino_ant = 'tr'+ str(int(semana_util - 1))
            semana_treino = 'pr'+ str(int(semana_util))
            qtd_treino = 'tr'+ str(int(semana_util))

            val_temp = df_week.loc[atl_index, semana_treino_ant] * 1.05
            qtd_temp = df_week.loc[atl_index, qtd_treino_ant] + 1

            if val_temp > 100:
                val_temp = 100
            
            if qtd_temp > 7:
                qtd_temp = 7
                
            df_week.at[atl_index, semana_treino] = val_temp
            df_week.at[atl_index, qtd_treino] = qtd_temp

            semana_util += 1

    return df_week

In [ ]:
def new_week(atlete_id, ano, semana_atual):
    
    #
    # Carrega df_week
    #
    
    for wk in df_week:
        soma_pr = int(0)
        for i in range(semana_atual):
            semana_util = semana_atual - i
            campo = 'pr' + str(int(semana_util))
            if wk[campo] > 0:
                x = 0
                break
            else:
                x = 1
        
        while semana_util < semana_atual and x == 0:
            semana_treino_ant = 'pr'+ str(int(semana_util - 1))
            qtd_treino_ant = 'tr'+ str(int(semana_util - 1))
            semana_treino = 'pr'+ str(int(semana_util))
            qtd_treino = 'tr'+ str(int(semana_util))

            val_temp = df_week.loc[atl_index, semana_treino_ant] * 1.05
            qtd_temp = df_week.loc[atl_index, qtd_treino_ant] + 1

            if val_temp > 100:
                val_temp = 100
            
            if qtd_temp > 7:
                qtd_temp = 7
                
            df_week.at[atl_index, semana_treino] = val_temp
            df_week.at[atl_index, qtd_treino] = qtd_temp

            semana_util += 1

In [418]:
now = datetime.now()
semana_atual = now.isocalendar()[1]
print(semana_atual)
df_ret = carrega_treino_novo(1, semana_atual, 1)
df_ret

36

,id_atl,sport,ano,data,qtd_tr,avg_tr,dsv_tr,pr1,tr1,pr2,...,pr48,tr48,pr49,tr49,pr50,tr50,pr51,tr51,pr52,tr52
0,1,RUN,2024,2024-08-29 16:46:37,132,41.033182,7.999035,41.82125,3,41.993137,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
1,1,ROAD,2024,2024-08-21 15:00:49,74,29.537568,12.572488,24.41250,3,33.737100,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
2,1,SWIM,2024,NaT,3,50.000000,33.000000,0.00000,0,0.000000,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
3,1,TRAIL,2024,2024-08-25 17:26:42,5,58.210000,33.196632,0.00000,0,0.000000,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
4,1,MTB,2024,2024-08-28 14:39:04,6,36.163333,27.586933,0.00000,0,0.000000,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0

In [366]:
df_ret.to_csv('PR_Chris.csv', sep=',', index=False)

In [406]:
for i in range(52):
    campo1 = 'pr' + str(int(i+1))
    campo2 = 'tr' + str(int(i+1))
    print(campo1, df_ret.loc[1, campo1], df_ret.loc[1, campo2])

pr1 24.4125 3
pr2 33.73709960937501 3
pr3 33.561599456787114 3
pr4 33.07419467916489 3
pr5 36.723803424286324 3
pr6 35.677495196625486 3
pr7 33.19389560050693 3
pr8 26.10851883134029 3
pr9 26.56721893476036 3
pr10 27.19438868334284 3
pr11 26.678560816099363 3
pr12 27.28952498200869 3
pr13 29.51537569249888 3
pr14 26.792045326286615 3
pr15 28.896945078128525 3
pr16 28.691224890077244 3
pr17 30.028378525526406 3
pr18 25.745834349984456 3
pr19 26.84484455061276 3
pr20 26.712736312705665 3
pr21 26.83377984625571 3
pr22 32.44074466627109 3
pr23 27.88148611388727 3
pr24 28.789170314686224 3
pr25 30.228628830420536 4
pr26 31.740060271941566 5
pr27 34.329219404615536 5
pr28 36.12845358323087 4
pr29 35.845925757435445 3
pr30 30.104406175363984 3
pr31 29.20471986309914 3
pr32 28.75341266914293 3
pr33 30.371859357712545 3
pr34 28.05587943314897 3
pr35 29.45867340480642 4
pr36 30.931607075046742 5
pr37 0.0 0
pr38 0.0 0
pr39 0.0 0
pr40 0.0 0
pr41 0.0 0
pr42 0.0 0
pr43 0.0 0
pr44 0.0 0
pr45 0.0 0
pr46 0.0 0
pr47 0.0 0
pr48 0.0 0
pr49 0.0 0
pr50 0.0 0
pr51 0.0 0
pr52 0.0 0

In [350]:
# 1 - Procurar treinos Garmin - Strava: Gravar treinos NoSQL
# 2 - Varrer Treinos
#
#.   Verificar se os treinos não calculados
#
#    para cada treino, CALCULAR O PR do TREINO
#
#.   Calcular por semana
#    1) Semana do treino
#.   2) verificar se semana já tem PR
#.   3) se não tiver buscar ultimo PR e vir atualizando semanalmente onde
#.      PR semana seguinte = PR semana anterior * 1,05    
#.      TR semana seguinte = TR semana anterior + 1    (3 <= TR <= 7)
#.      Até chegar na semana do treino
#
#    4) Se tiver 
#.      Tr semana = TR semana -1 (se TR < 3 TR = 3)
#       Calcular 
#.      (PR samana * TR + PR treino) / (TR +1)

(10+46)/2

28.0